---
title: Trafikkregistreringspunkter i fartsgrense 80 km/h
output: 
  html_document:
    toc: true
    fig_caption: true
---

```{r setup, include = FALSE, echo = FALSE}
source("H:/Programmering/R/byindeks/rmd_setup.R")
library(htmltools)
```

```{r points, include = FALSE}
all_point_info <- 
  read.csv2("punkter_med_fartsgrense_80.csv")

```

Kartet nedenfor viser plasseringen av trafikkregistreringspunktene som er igangsatt før 1. januar 2018.

```{r map_trp}
# labels on two lines
labs <- lapply(seq(nrow(all_point_info)), function(i) {
  paste0( '<p>', 
          all_point_info[i, "name"], 
          '<p></p>', 
          all_point_info[i, "road_reference"], 
          '</p>' ) 
})

all_point_info %>%
  leaflet(width = "100%",
          options = leafletOptions(crs = nvdb_crs,
                                   zoomControl = F)) %>%
  addTiles(urlTemplate = nvdb_map_url,
           attribution = nvdb_map_attribution) %>%
  addCircleMarkers(
    radius = 6,
    stroke = T,
    weight = 2,
    color = "#444f55",
    opacity = 0.8,
    fill = T,
    #fillColor = ~palett_adt(adt),
    fillOpacity = 0.4,
    label = lapply(labs, htmltools::HTML)
  )
```

