---
title: "Radarregistreringer 2020"
output: html_notebook
---

```{r setup, include = FALSE, echo = FALSE}
source("H:/Programmering/R/byindeks/rmd_setup.R")
library(htmltools)
```

```{r points, include = FALSE}
radar_measurements <- 
  read.csv2("periodic_data/toporegistreringer_2020.csv")

radar_points <-
  read.csv2("periodic_data/topopunkt_2020.csv")
```

```{r map_trp}
# labels on two lines
labs <- lapply(seq(nrow(radar_measurements)), function(i) {
  paste0( '<p>', 
          radar_measurements[i, "latitude"], 
          '<p></p>', 
          radar_measurements[i, "longitude"], 
          '</p>' ) 
})

leaflet(width = "100%",
        options = leafletOptions(crs = nvdb_crs,
                                 zoomControl = F)) %>%
  addTiles(urlTemplate = nvdb_map_url,
           attribution = nvdb_map_attribution) %>%
  addCircleMarkers(
    data = radar_measurements,
    radius = 6,
    stroke = T,
    weight = 2,
    color = "#444f55",
    opacity = 0.8,
    fill = T,
    fillOpacity = 0.4,
    label = lapply(labs, htmltools::HTML)
  ) %>% 
  addCircleMarkers(
    data = radar_points,
    radius = 3,
    stroke = T,
    weight = 2,
    color = "#008ec2",
    opacity = 0.9,
    fill = T,
    fillOpacity = 0.7
  )
```
