---
title: "Trafikklenker"
output: html_notebook
---

```{r setup, include = FALSE, echo = FALSE}
# Packages ####
library(tidyverse)
library(leaflet)
library(sf)
library(knitr)
library(flextable)
library(htmltools)
library(DBI)
library(RSQLite)

source("H:/Programmering/R/byindeks/get_from_nvdb_api.R")
source("H:/Programmering/R/byindeks/get_from_trafficdata_api.R")
source("H:/Programmering/R/byindeks/split_road_system_reference.R")

# knitr options ####
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      cache = FALSE)

# Map essentials ####
nvdb_map_url <-
  "https://nvdbcache.geodataonline.no/arcgis/rest/services/Trafikkportalen/GeocacheTrafikkJPG/MapServer/tile/{z}/{y}/{x}"

nvdb_map_attribution <-
  "NVDB, Geovekst, kommunene og Open Street Map contributors (utenfor Norge)"

nvdb_crs <- leafletCRS(
  crsClass = "L.Proj.CRS", code = "EPSG:25833",
  proj4def = "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs",
  resolutions = c(
    21674.7100160867,
    10837.35500804335,
    5418.677504021675,
    2709.3387520108377,
    1354.6693760054188,
    677.3346880027094,
    338.6673440013547,
    169.33367200067735,
    84.66683600033868,
    42.33341800016934,
    21.16670900008467,
    10.583354500042335,
    5.291677250021167,
    2.6458386250105836,
    1.3229193125052918,
    0.6614596562526459,
    0.33072982812632296,
    0.16536491406316148
  ),
  origin = c(-2500000.0, 9045984.0))

#alle_kommune_polygoner <- hent_alle_kommuner_v3()
kommuner <- get_municipalities()
```


```{r file_path, include=FALSE}
#geopackage_file <- "Trafikklenkekandidater_20201021.gpkg"
geopackage_file <- "Trafikklenker_20210317104831.gpkg"

# To see layers in gpkg file
layers <- sf::st_layers(geopackage_file)
```

```{r explore_rows, message=FALSE, include=FALSE}
# Exploring the top rows
#top_row_query <- "SELECT * FROM \"TrafikkLenker\" WHERE geometry IS NOT NULL AND min_funksjonell_vegklasse IS 2 LIMIT 10"
#top_row_query <- "SELECT * FROM \"TrafikkLenker\" LIMIT 10"
#top_row_query <- "SELECT feature_oid, start_node_oid, end_node_oid FROM \"TrafikkLenker\" WHERE geometry IS NOT NULL LIMIT 15"
# trafikklenker_selected <- sf::st_read(geopackage_file, "TrafikkLenker",
#                                  as_tibble = TRUE,
#                                  query = top_row_query)



#link_query <- "SELECT * FROM \"TrafikkLenker\" WHERE start_node_oid IN(3283021)"
link_query <- "SELECT * FROM \"TrafikkLenker\" WHERE roadref_category IS 'R' AND roadref_number IS 13"
#link_query <- "SELECT * FROM \"TrafikkLenker\" WHERE id IN('e18dc778-b686-435c-b77d-2460e4ea421d')"
trafikklenker_selected <- sf::st_read(geopackage_file, "TrafikkLenker",
                                      as_tibble = TRUE,
                                      query = link_query)

trafikklenker_selected_2 <- trafikklenker_selected %>% 
  tidyr::separate(MUNICIPALITY, into = c("municipality_1", "municipality_2"),
                  sep = ",", fill = "right") %>% 
  dplyr::mutate(county_1 = stringr::str_sub(municipality_1, 1, 2)) %>% 
  dplyr::filter(county_1 %in% c("11", "46"))

trafikklenker_selected <- trafikklenker_selected_2

# trafikklenker_selected %>% 
#   sf::st_drop_geometry() %>% 
#   dplyr::select(trafikklenkeid = FEATURE_OID,
#                 startnode = START_NODE_OID,
#                 sluttnode = END_NODE_OID) %>% 
#   write.csv2(file = "trafikklenkeseksempel.csv",
#              row.names = FALSE)

# top_row_query_null <- "SELECT feature_oid FROM \"TrafikkLenker\" WHERE geometry IS NULL"
# trafikklenker_top_null <- sf::st_read(geopackage_file, "TrafikkLenker",
#                                  as_tibble = TRUE,
#                                  query = top_row_query_null)

#top_row_query_kryss <- "SELECT * FROM \"Kryss\" LIMIT 100"
#top_row_query_kryss <- "SELECT * FROM \"Kryss\" WHERE feature_oid IS '1108 F516 S1D1 m218 KD1' LIMIT 100"
# kryss_top <- sf::st_read(geopackage_file, "Kryss",
#                              as_tibble = TRUE,
#                              query = top_row_query_kryss)

# stedfestinger <- "SELECT * FROM \"Trafikklenker_stedfesting\" WHERE feature_oid IN ()"
# trafikklenker_top_null <- sf::st_read(geopackage_file, "TrafikkLenker",
#                                  as_tibble = TRUE,
#                                  query = top_row_query_null)




# Looking at a specific road segment
# E39 Førde: 384479
# Harsjøen: IN (705126, 705125) 
#element_query <- "SELECT * FROM \"Trafikklenker\" WHERE ELEMENT_ID BETWEEN 705100 AND 705200"
#element_query <- "SELECT * FROM \"Trafikklenker\" WHERE ELEMENT_ID IN (705126, 705125, 705238, 705127)"
# Klett
#element_query <- "SELECT * FROM \"TrafikkLenker\" WHERE ELEMENT_ID IN (3112188, 3112207, 2997535, 2997537, 2997540, 2997539, 3112180, 3112181, 2997528, 2997531, 3112190, 3112189, 2997529, 3112179, 72241, 72242, 2801072)"

# Read many
#element_query <- "SELECT feature_oid, start_node_oid, end_node_oid, geometry FROM \"Trafikklenker\" LIMIT 50000;"
#element_query <- "SELECT * FROM \"Trafikklenker\" LIMIT 5;"

# trafikklenker_element <- sf::st_read(geopackage_file, "TrafikkLenker",
#                                      as_tibble = TRUE,
#                                     query = element_query)
```

```{r query_sqlite}
# Spør direkte til SQLite-databasen
# databasekobling <- DBI::dbConnect(SQLite(), geopackage_file)
# databasetabeller <- as.data.frame(dbListTables(databasekobling))
# 
# distinct_vegklasser <- paste0(
#   "SELECT min_funksjonell_vegklasse, ",
#   "COUNT(*) ",
#   "FROM TrafikkLenker ",
#   "GROUP BY min_funksjonell_vegklasse;")

# sql_query_for_null_geometry <- paste0(
#   "SELECT feature_oid, element_id, start_measure, end_measure ",
#   "FROM TrafikkLenker ",
#   "INNER JOIN Trafikklenker_stedfesting ",
#   "USING(feature_oid) ",
#   "WHERE TrafikkLenker.geometry IS NULL")

#sql_query <- distinct_vegklasser
 
#sporring <- DBI::dbSendQuery(databasekobling, sql_query)

#resultat <- DBI::dbFetch(sporring)

#dbClearResult(lenker_uten_geometri_med_stedfesting)

# Skrur av kobling til databasen
#DBI::dbDisconnect(databasekobling)
# 
# lenker_uten_geometri_med_stedfesting_veglenkeposisjon <- lenker_uten_geometri_med_stedfesting_resultat %>%
#   #slice(3081:3090) %>% 
#   dplyr::mutate(roadlink_position_start = paste0(START_MEASURE, "@", ELEMENT_ID),
#                 roadlink_position_end = paste0(END_MEASURE, "@", ELEMENT_ID),
#                 road_system_reference_start = mapply(hent_vegsystemreferanse, 
#                                                      roadlink_position_start,
#                                                      USE.NAMES = FALSE),
#                 #road_system_reference_start = purrr::map_chr(roadlink_position_start,
#                 #                                             hent_vegsystemreferanse)
#                 )
# 
# lenker_uten_geometri_med_stedfesting_veglenkeposisjon %>% 
#   write.csv2(file = "trafikklenker_uten_geometri.csv",
#              row.names = F)
```


```{r stedfesting}
#query_stedfesting <- "SELECT * FROM \"Trafikklenker_stedfesting\" WHERE element_id IN(3112184)"
# query_stedfesting <- "SELECT * FROM \"Trafikklenker_stedfesting\" WHERE feature_oid IN('5caf5717-4f1e-42ee-9dd1-51f810c365c3')"
# trafikklenker_stedfesting <- sf::st_read(geopackage_file, "Trafikklenker_stedfesting",
#                                          as_tibble = TRUE,
#                                          query = query_stedfesting)
# 
# trafikklenker_stedfesting %>% 
#   sf::st_drop_geometry() %>% 
#   dplyr::select(veglenkesekvensid = ELEMENT_ID,
#                 startposisjon = START_MEASURE,
#                 sluttposisjon = END_MEASURE) %>% 
#   write.csv2(file = "stedfestingseksempel.csv",
#              row.names = FALSE)

```




```{r intersections}
# Tilhørende kryss
unique_start_node_ids <- trafikklenker_selected$START_NODE_OID %>% 
   unique()
unique_end_node_ids <- trafikklenker_selected$END_NODE_OID %>% 
   unique()
 
unique_node_ids <- c(unique_start_node_ids, unique_end_node_ids) %>% 
  unique() %>% 
  stringr::str_c(collapse = "\', \'")
 
kryss_query = paste0("SELECT * FROM \"Kryss\" WHERE FEATURE_OID IN (",
                     "\'", unique_node_ids, "\'", ")")
 
kryss <- sf::st_read(geopackage_file, "Kryss",
                     as_tibble = TRUE,
                      query = kryss_query) %>% 
   sf::st_zm(drop = T, what = "ZM") %>% 
   #dplyr::select(GEOMETRY) %>% 
   sf::st_transform("+proj=longlat +datum=WGS84")
```



```{r transform_geometry}
trafikklenker_combined <- trafikklenker_selected %>%
  sf::st_zm(drop = T, what = "ZM") %>% 
  dplyr::rename(road_reference = ROADREF_START) %>% 
  split_road_system_reference() %>% 
  dplyr::select(ID, START_NODE_OID, END_NODE_OID,
                ROADREF_START = road_reference, ROADREF_END, ROADREF_NUMBER,ROADREF_CATEGORY,
                DIRECTION, COMMENT) %>% 
  #dplyr::select(GEOMETRY, ID) %>% 
  #dplyr::group_by(FEATURE_OID) %>% 
  #dplyr::summarise(combined_geometry = sf::st_combine(GEOMETRY)) %>% 
  dplyr::mutate(line_length = round(sf::st_length(GEOMETRY),
                                    digits = 0)) %>% 
  dplyr::mutate(link_label = paste(ROADREF_START, ROADREF_END, line_length,
                                   START_NODE_OID, END_NODE_OID,
                                   sep = "<br/>"),
                link_label = lapply(link_label, htmltools::HTML)) %>% 
  # Need to transform for leaflet plotting
  sf::st_transform("+proj=longlat +datum=WGS84")

# TODO: transform all combined, and write to file
# TODO: find road system reference segment for each link

# Filter by municipality polygon
#kommunenr <- alle_kommuner$nummer[alle_kommuner$navn == "Trondheim"] %>% 
#  as.character()

#kommune_polygon <- hent_kommune_v3(kommunenr)
# TODO: Consider simplifying polygon by st_simplify

#trafikklenker_kommune <- trafikklenker_combined %>% 
#  dplyr::mutate(innafor = sf::st_intersects(trafikklenker_combined, kommune_polygon, sparse = FALSE))

#trafikklenker_trondheim <- trafikklenker_kommune %>% 
#  filter(innafor == TRUE)
```


```{r map_links}
leaflet(width = "100%",
        height = 700,
        options = leafletOptions(crs = nvdb_crs,
                                 zoomControl = F)) %>%
  addTiles(urlTemplate = nvdb_map_url,
           attribution = nvdb_map_attribution) %>%
  addPolylines(data = trafikklenker_combined, #trafikklenker_trondheim,
               popup = ~link_label,
               highlightOptions = highlightOptions(bringToFront = TRUE,
                                                   sendToBack = FALSE,
                                                   color = "red",
                                                   opacity = 0.6)) %>% 
  addCircleMarkers(data = kryss,
                   popup = ~FEATURE_OID,
                   radius = 5,
                   stroke = FALSE,
                   fillOpacity = 0.9,
                   fill = TRUE,
                   fillColor = "black") #%>%
  #addPolygons(data = kommune_polygon,
  #            fill = FALSE)
```


```{r ggplot_links}
# ggplot2::ggplot(trafikklenker_combined) +
#   geom_sf()
```



```{r histogram}
# trafikklenker_combined %>%
#   dplyr::mutate(numeric_lengths = as.numeric(line_length)) %>%
#   ggplot2::ggplot(aes(x = numeric_lengths)) +
#   ggplot2::geom_histogram(binwidth = 1000) +
#   ggplot2::theme_minimal() +
#   ggplot2::ggtitle("Fordeling av trafikklenkenes lengder (m)")
```

