---
title: "Trafikklenker og trafikkregistreringspunkt"
output: html_notebook
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(leaflet)
library(sf)
library(knitr)
library(htmltools)
library(geojsonsf)
library(DBI)
library(RSQLite)

source("H:/Programmering/R/byindeks/get_from_nvdb_api.R")
source("H:/Programmering/R/byindeks/get_from_trafficdata_api.R")
source("H:/Programmering/R/byindeks/split_road_system_reference.R")

# knitr options ####
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      cache = FALSE)

# Map essentials ####
nvdb_map_url <-
  "https://nvdbcache.geodataonline.no/arcgis/rest/services/Trafikkportalen/GeocacheTrafikkJPG/MapServer/tile/{z}/{y}/{x}"

nvdb_map_attribution <-
  "NVDB, Geovekst, kommunene og Open Street Map contributors (utenfor Norge)"

nvdb_crs <- leafletCRS(
  crsClass = "L.Proj.CRS", code = "EPSG:25833",
  proj4def = "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs",
  resolutions = c(
    21674.7100160867,
    10837.35500804335,
    5418.677504021675,
    2709.3387520108377,
    1354.6693760054188,
    677.3346880027094,
    338.6673440013547,
    169.33367200067735,
    84.66683600033868,
    42.33341800016934,
    21.16670900008467,
    10.583354500042335,
    5.291677250021167,
    2.6458386250105836,
    1.3229193125052918,
    0.6614596562526459,
    0.33072982812632296,
    0.16536491406316148
  ),
  origin = c(-2500000.0, 9045984.0))
```

```{r traffic_links_from_nvdb}
ev6_viken <- 
  get_traffic_links("&kommune=3030,3033&vegsystemreferanse=E,R")

# the query does not support pagination yet

traffic_link_positions <- dplyr::bind_rows(
  ev6_viken$veglenkeposisjoner
)

traffic_link_geometries <- dplyr::bind_rows(
  ev6_viken$geometri
)

traffic_link_road_references <- dplyr::bind_rows(
  ev6_viken$vegreferanser
)

traffic_link_road_info <-
  traffic_link_road_references %>% 
  dplyr::select(
    object_id,
    road,
    road_category,
    length_m
  ) %>% 
  dplyr::distinct()
```


```{r points}
points <- get_points() %>%
  dplyr::distinct(trp_id, .keep_all = T) %>%
  dplyr::mutate(name = stringr::str_to_title(name, locale = "no"))

points_metadata <- points %>%
  dplyr::filter(
    traffic_type == "VEHICLE",
    operational_status %in% c("OPERATIONAL", "TEMPORARILY_OUT_OF_SERVICE")) %>% 
#  split_road_system_reference() %>%
  dplyr::select(
    trp_id, 
    name, 
    registration_frequency,
    #road_category_and_number,
    road_reference,
    lane_numbers,
    county_geono, 
    county_name, 
    municipality_name,
    lat, lon, 
    road_network_position, road_network_link, road_link_position
  ) %>% 
  dplyr::mutate(
    road_network_link = as.character(road_network_link)
  ) %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(
    lanes = sort(lane_numbers) %>% 
      paste(collapse = ", ")
  ) %>% 
  ungroup() %>% 
  dplyr::select(
    -lane_numbers
  )

# Special request
# points_metadata_bike <- points %>%
#   dplyr::filter(
#     traffic_type == "BICYCLE"
#     ) %>% 
#   split_road_system_reference() %>%
#   dplyr::select(
#     trp_id, 
#     name, 
#     road_category_and_number,
#     road_reference,
#     county_geono, 
#     county_name, 
#     municipality_name,
#     lat, lon, 
#     road_network_position, road_network_link, road_link_position
#   ) %>% 
#   sf::st_as_sf(
#     coords = c("lon", "lat"),
#     crs = 4326
#   )
# 
# points_metadata_bike %>% 
# sf::write_sf(
#     "spesialbestillinger/sykkelregistreringspunkt.gpkg",
#     quiet = FALSE,
#     append = FALSE
#   )
```

```{r traffic_links_from_gpkg, include=FALSE}
geopackage_file <- "trafikklenker/Trafikklenker_20220116.gpkg"

# To see layers in gpkg file
#layers <- sf::st_layers(geopackage_file)
```

```{r traffic_link_exploration}
query_position <- "SELECT * FROM \"Trafikklenker_stedfesting\""

trafikklenker_stedfesting_selected <- 
  sf::st_read(
    geopackage_file, 
    as_tibble = TRUE,
    query = query_position
  )

# trafikklenker <-
#   sf::st_read(
#     geopackage_file,
#     as_tibble = TRUE,
#     query = "SELECT * FROM \"TrafikkLenker\" LIMIT 2"
#   )
```


```{r data_prep_nvdb}
trps_on_links <- traffic_link_positions %>%
  dplyr::left_join(
    points_metadata,
    by = c("veglenkesekvensid" = "road_network_link")
  ) %>% 
  dplyr::mutate(
    on_link = road_network_position > startposisjon & road_network_position < sluttposisjon,
    length_m = round(length_m)
  ) %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(
    lanes = sort(lane_numbers) %>% 
      paste(collapse = ", ")
  ) %>% 
  ungroup() %>% 
  dplyr::filter(
    on_link == TRUE
  ) %>% 
  dplyr::select(
    object_id,
    trp_id,
    name,
    registration_frequency,
    lanes,
    county_name,
    municipality_name,
    lat, lon
  )

traffic_link_geometries_and_trp <-
  traffic_link_geometries %>% 
  dplyr::left_join(
    trps_on_links, by = "object_id"
  ) %>% 
  dplyr::select(
    -year
  ) %>% 
  dplyr::left_join(
    traffic_link_road_info,
    by = "object_id"
  ) %>%
  dplyr::group_by(
    object_id
  ) %>% 
  dplyr::slice_head() %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(
    has_trp = !is.na(trp_id)
  ) %>% 
  dplyr::mutate(
    link_label = paste(trp_id, "<br/>",
                       name, "<br/>",
                       registration_frequency,  "<br/>",
                       "Felt: ", lanes, "<br/>",
                       length_m, " m"
                       ),
    link_label = lapply(link_label, htmltools::HTML))

# Write to file for further processing in ArcGIS
traffic_link_geometries_and_trp %>% 
  dplyr::select(
    -link_label,
    -lokasjon.geometri.srid
  ) %>% 
  sf::write_sf(
    "trafikklenker/trafikklenker_med_trp.gpkg",
    quiet = FALSE,
    append = FALSE
  )

geopackage_file <- "trafikklenker/trafikklenker_med_trp.gpkg"

# To see layers in gpkg file
layers <- sf::st_layers(geopackage_file)

link_query <- "SELECT * FROM \"trafikklenker_med_trp\""

test <- 
  sf::st_read(
    geopackage_file, 
    as_tibble = TRUE,
    query = link_query
  )


```

```{r data_prep_gpkg}
trps_on_links <- 
  trafikklenker_stedfesting_selected %>%
  dplyr::left_join(
    points_metadata,
    by = c("ELEMENT_ID" = "road_network_link")
  ) %>% 
  dplyr::mutate(
    on_link = road_network_position > START_MEASURE & road_network_position < END_MEASURE,
    on_link = dplyr::if_else(is.na(on_link), FALSE, on_link),
    on_link = dplyr::if_else(on_link == FALSE, 0, 1)
  ) %>% 
  dplyr::select(
    FEATURE_OID,
    on_link
  ) %>% 
  dplyr::group_by(
    FEATURE_OID
  ) %>% 
  dplyr::summarise(
    n_trp = sum(on_link)
  )

# Make a copy of the original GPKG
# Keep only the TrafikkLenker layer
# Add a a column with n trps to this layer
# Add a layer with all trps and their geometry
```

```{r query_sqlite}
# Lager en kopi av Trionas GPKG-fil og tukler med den
# HA den på C slik at ikke nettutfall stopper skrivingen,
# og kanskje det går raskere
#new_gpkg_file <- "trafikklenker/Trafikklenker_triona_med_trp.gpkg"
new_gpkg_file <- "C:/Users/snohan/Desktop/Trafikklenker_triona_med_trp_2.gpkg"

# trps_on_links %>%
#   sf::write_sf(
#     new_gpkg_file,
#     layer = "links_and_trps",
#     quiet = FALSE,
#     append = TRUE
#   )

points_metadata %>% 
  sf::st_as_sf(
    coords = c("lon", "lat"),
    crs = 4326
  ) %>% 
  sf::write_sf(
    new_gpkg_file,
    layer = "TRP",
    quiet = FALSE,
    append = TRUE
  )

trafikklenker <-
  sf::st_read(
    new_gpkg_file,
    as_tibble = TRUE,
    query = "SELECT * FROM \"TrafikkLenker\""
  )

trafikklenker_og_n_trp <-
  trafikklenker %>% 
  dplyr::left_join(
    trps_on_links,
    by = c("ID" = "FEATURE_OID")
  )

trafikklenker_og_n_trp %>%
  sf::write_sf(
    new_gpkg_file,
    layer = "TrafikkLenker",
    quiet = FALSE,
    append = FALSE
  )

# Spør direkte til SQLite-databasen
# databasekobling <- 
#   DBI::dbConnect(
#     RSQLite::SQLite(), 
#     new_gpkg_file
#   )
# 
# databasetabeller <- as.data.frame(dbListTables(databasekobling))
# 
# DBI::dbSendQuery(databasekobling, "DROP TABLE test;")
# 
# create_link_table <-
#   "CREATE TABLE TrafikkLenker_med_n_trp AS SELECT * FROM TrafikkLenker LEFT JOIN links_and_trps ON TrafikkLenker.ID = links_and_trps.FEATURE_OID"
# 
# DBI::dbSendQuery(databasekobling, create_link_table)

# Checking
# trafikklenker_med_n_trp_selected <- 
#   sf::st_read(
#     new_gpkg_file, 
#     as_tibble = TRUE,
#     query = "SELECT * FROM TrafikkLenker_med_n_trp LIMIT 3"
#   )

layers <- sf::st_layers(new_gpkg_file)

# Remove old link table to reduce file size (but no reduction?)
#DBI::dbSendQuery(databasekobling, "DROP TABLE TrafikkLenker;")

# Skrur av kobling til databasen
#DBI::dbDisconnect(databasekobling)
```


```{r map_function}
create_trafficlink_map <- function() {
  
  colors_has_trps <-
    colorFactor(palette = c("#db3b99", "#444f55"),
                domain = c(TRUE, FALSE))

  map <- 
    leaflet(
      width = "100%",
      height = 700,
      options = leafletOptions(
        crs = nvdb_crs,
        zoomControl = TRUE
        )
      ) %>%
  addTiles(
    urlTemplate = nvdb_map_url,
    attribution = nvdb_map_attribution
    ) %>%
  addPolylines(
    data = traffic_link_geometries_and_trp,
    label = ~link_label,
    opacity = 0.8,
    #fill = T,
    #fillColor = ~palett_index(aadt_diff),
    color = ~colors_has_trps(has_trp),
    #fillColor = ~palett_index(aadt_df$aadt_diff),
    #fillOpacity = 0.9,
    highlightOptions = highlightOptions(
      bringToFront = TRUE,
      sendToBack = FALSE,
      color = "red",
      opacity = 0.6
      )
    ) %>%
    addLegend(
      "bottomright",
      pal = colors_has_trps,
      values = traffic_link_geometries_and_trp$has_trp,
      title = "Lenke med TRP",
      opacity = 0.8,
      labFormat = labelFormat(big.mark = " ")
      )
  
  return(map)
}

```

```{r map}
create_trafficlink_map()
```















