---
title: "Modellberegnet ÅDT sammenlignet med \"manuell\" ÅDT-belegging"
output: 
  html_document:
    css: svv.css
    number_sections: true
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
fig_width: 5
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(leaflet)
library(sf)
library(knitr)
library(htmltools)
library(geojsonsf)

source("H:/Programmering/R/byindeks/get_from_nvdb_api.R")
source("H:/Programmering/R/byindeks/get_from_trafficdata_api.R")
source("H:/Programmering/R/byindeks/split_road_system_reference.R")

# knitr options ####
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      cache = FALSE)

# Map essentials ####
nvdb_map_url <-
  "https://nvdbcache.geodataonline.no/arcgis/rest/services/Trafikkportalen/GeocacheTrafikkJPG/MapServer/tile/{z}/{y}/{x}"

nvdb_map_attribution <-
  "NVDB, Geovekst, kommunene og Open Street Map contributors (utenfor Norge)"

nvdb_crs <- leafletCRS(
  crsClass = "L.Proj.CRS", code = "EPSG:25833",
  proj4def = "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs",
  resolutions = c(
    21674.7100160867,
    10837.35500804335,
    5418.677504021675,
    2709.3387520108377,
    1354.6693760054188,
    677.3346880027094,
    338.6673440013547,
    169.33367200067735,
    84.66683600033868,
    42.33341800016934,
    21.16670900008467,
    10.583354500042335,
    5.291677250021167,
    2.6458386250105836,
    1.3229193125052918,
    0.6614596562526459,
    0.33072982812632296,
    0.16536491406316148
  ),
  origin = c(-2500000.0, 9045984.0))
```


```{r todos}
# TODO: load model predictions from gpkg
# TODO: add model AADTs to undirected links
# TODO: fetch manual AADT from NVDB
# TODO: compare statistically
# TODO: map with visualised differences
```

# Bakgrunn
Norsk Regnesentral har utviklet en modell for maskinell ÅDT-belegging av vegnettet. ÅDT-estimater fra denne modellen er her sammenlignet med den "manuelle" ÅDT-beleggingen.


```{r gdb}
# klepp <- sf::st_read("trafikklenker/klepp.gdb")
# kinn <- sf::st_read("trafikklenker/kinn.gdb")
# kinn <- sf::read_sf("trafikklenker/kinn.gdb")
# vestland <- sf::st_read("trafikklenker/vestland_erf.gdb")
# vestland <- geojsonsf::geojson_sf("trafikklenker/vestland_erf.gdb")
```


```{r file_path, include=FALSE}
# Model predictions for Vestland and Rogaland
geopackage_file <- 
"nr_prep_links/trafikklenker_dir_rv_2021_preproc_predaadt_balaadt_noder-kanter-kategorisert.gpkg"
#layers <- sf::st_layers(geopackage_file)
```

```{r explore_rows, message=FALSE, include=FALSE}
#link_query <- "SELECT * FROM \"edges_rv\" LIMIT 10"
link_query <- "SELECT id, direction, municipality, med_metrering, roadref_category, roadref_number, aadt_alle_mean, pred_aadt, pred_aadt_sd, aadt_prelim, aadt_prelim_sd, aadt_bal, aadt_bal_sd, aadt_bal_tot, geom FROM \"edges_rv\" WHERE (roadref_category = 'F' AND roadref_number = 44)"
#top_row_query <- "SELECT feature_oid, start_node_oid, end_node_oid FROM \"TrafikkLenker\" WHERE geometry IS NOT NULL LIMIT 15"
#link_query <- "SELECT * FROM \"TrafikkLenker\" WHERE start_node_oid IN(3283021)"
links_selected <- 
  sf::st_read(
    geopackage_file, 
    as_tibble = TRUE,
    query = link_query,
    quiet = TRUE
  )

links_selected_id <- 
  links_selected %>% 
  dplyr::select(ID) %>% 
  dplyr::distinct()
```

```{r transform_geometry}
traffic_links_wide <- 
  links_selected %>%
  dplyr::select(
    ID,
    roadcat = ROADREF_CATEGORY,
    roadn = ROADREF_NUMBER,
    with = med_metrering,
    aadt_bal,
    pred_aadt,
    #sd = pred_aadt_sd,
    trp_aadt = aadt_prelim,
    tm_aadt = AADT_ALLE_MEAN#,
    #nettaadt_mangler
  ) %>% 
  sf::st_drop_geometry() %>% 
  tidyr::pivot_wider(
    names_from = with,
    names_prefix = "med_",
    values_from = c(aadt_bal, pred_aadt, trp_aadt, tm_aadt)
  ) %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(
    aadt_bal = sum(aadt_bal_med_0, aadt_bal_med_1, na.rm = TRUE),
    pred_aadt = sum(pred_aadt_med_0, pred_aadt_med_1, na.rm = TRUE),
    trp_aadt = sum(trp_aadt_med_0, trp_aadt_med_1, na.rm = TRUE),
    tm_aadt = sum(tm_aadt_med_0, tm_aadt_med_1, na.rm = TRUE)
    #,
    #sd = dplyr::case_when(
      ## if one or both directions are missing
      #is.na(pred_aadt_med_1) || is.na(pred_aadt_med_0) ~ 
      #  sum(sd_med_1, sd_med_0, na.rm = TRUE),
      ## when both is present, combined sd
      #TRUE ~ sqrt((sd_med_1^2 + sd_med_0^2)/2 + 
      #  ((pred_aadt_med_1 - pred_aadt_med_0)/2)^2)
    #)
  ) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(
    across(
      .cols = c(
        aadt_bal_med_1,
        aadt_bal_med_0,
        pred_aadt_med_1, 
        pred_aadt_med_0,
        #sd_med_1, 
        #sd_med_0,
        trp_aadt_med_1,
        trp_aadt_med_0,
        tm_aadt_med_1, 
        tm_aadt_med_0,
        aadt_bal,
        pred_aadt,
        trp_aadt,
        tm_aadt
        #sd
        ),
      ~ round(.x)
    )
  ) %>% 
  dplyr::select(
    ID,
    aadt_bal,
    pred_aadt,
    trp_aadt,
    tm_aadt
  )

traffic_links_transformed <- 
  links_selected_id %>% 
  dplyr::left_join(
    traffic_links_wide, 
    by = "ID"
  ) %>% 
  sf::st_zm(drop = T, what = "ZM") %>% 
  dplyr::mutate(
    line_length = 
      round(
        sf::st_length(geom),
        digits = 0)
  ) %>% 
  dplyr::mutate(
    link_label = 
      paste(
        "Balansert: ", aadt_bal, "<br/>",
        "Predikert: ", pred_aadt, "<br/>",
        "TM: ", tm_aadt, "<br/>",
        "TRP: ", trp_aadt, "<br/>",
        line_length, " m"
      ),
    # link_label = 
    #   paste(
    #     "Modell-ÅDT ", aadt, "S: ", sd, "TM:", tm_aadt, "<br/>",
    #     "Med ", pred_aadt_med_1, "S: ", sd_med_1, 
    #     "TM-ÅDT: ", tm_aadt_med_1,  "<br/>",
    #     "Mot ", pred_aadt_med_0, "S: ", sd_med_0, 
    #     "TM-ÅDT: ", tm_aadt_med_0, "<br/>",
    #     line_length, " m"
    #   ),
    link_label = lapply(link_label, htmltools::HTML)) %>% 
  sf::st_transform("+proj=longlat +datum=WGS84")

```

```{r compare}
# Try Rv 15
# manual_adt_rv15 <- get_aadt_by_road("RV15") %>% 
#   dplyr::filter(
#     purrr::map_lgl(
#       county_numbers, ~ 46 %in% .)
#   )
# 
# manual_adt_rv5 <- get_aadt_by_road("RV5") %>% 
#   dplyr::filter(
#     purrr::map_lgl(
#       county_numbers, ~ 46 %in% .)
#   )
# 
# manual_adt_ev16 <- get_aadt_by_road("EV16") %>% 
#   dplyr::filter(
#     purrr::map_lgl(
#       county_numbers, ~ 46 %in% .)
#   )
# 
# manual_adt <- 
#   dplyr::bind_rows(
#     manual_adt_rv5,
#     manual_adt_rv15,
#     manual_adt_ev16
#   )
# 
# nr_model <- 
#   traffic_links_transformed %>% 
#   dplyr::filter(roadn %in% c(5, 15, 16))



manual_adt_fv44 <- get_aadt_by_road("FV44")


# test <- sf::st_intersects(
#   nr_model_rv15$geom[1],
#   manual_adt_rv15$geometry
#   ) %>% 
#   unlist()

matchende <- 
  sf::st_join(
    traffic_links_transformed,
    manual_adt_fv44,
    largest = TRUE
  ) %>% 
  dplyr::mutate(
    aadt_diff = round((aadt_bal - aadt_total) / aadt_total * 100, digits = 0),
    link_label_final = paste0(link_label,
                              "<br/>", 
                              "NVDB: ", aadt_total, " Kilde: ", source),
    link_label_final = lapply(link_label_final, htmltools::HTML)
  ) %>% 
  dplyr::select(-link_label)

# Three links do not match along Oppstrynsvatnet, as it seems
# the geometry is a little moved to the side. Has something changed to 
# its geometry in NVDB since the traffic link was genereated?
# An st_buffer must be set in UTM
```


Sammenligning mellom predikert ÅDT fra Norsk Regnesentrals modell og manuell ÅDT-belegging.

```{r map_function}
create_aadt_comparison_map <- function(aadt_df) {
  
  # Create a red-green scale based on index values
  negative_value <- round(abs(min(aadt_df$aadt_diff, na.rm = T)), digits = 0) + 1
  positive_value <- round(max(aadt_df$aadt_diff, na.rm = T), digits = 0) + 1

  # If even the max value is negative
  if(positive_value < 0) positive_value <- 1

  rc1 <- colorRampPalette(
    colors = c("purple", "green"), 
    space = "Lab")(negative_value)

  ## Make vector of colors for values larger than 0 (180 colors)
  rc2 <- colorRampPalette(
    colors = c("green", "orange"), 
    space = "Lab")(positive_value)

  ## Combine the two color palettes
  rampcols <- c(rc1, rc2)

  palett_index <-
    leaflet::colorNumeric(
      palette = rampcols,
      domain = NULL
      )

  aadt_map <- 
    leaflet(
      width = "100%",
      height = 700,
      options = leafletOptions(
        crs = nvdb_crs,
        zoomControl = TRUE
        )
      ) %>%
  addTiles(
    urlTemplate = nvdb_map_url,
    attribution = nvdb_map_attribution
    ) %>%
  addPolylines(
    data = aadt_df,
    label = ~link_label_final,
    opacity = 0.8,
    #fill = T,
    #fillColor = ~palett_index(aadt_diff),
    color = ~palett_index(aadt_diff),
    #fillColor = ~palett_index(aadt_df$aadt_diff),
    #fillOpacity = 0.9,
    highlightOptions = highlightOptions(
      bringToFront = TRUE,
      sendToBack = FALSE,
      color = "red",
      opacity = 0.6
      )
    ) %>%
    addLegend(
      "bottomright",
      pal = palett_index,
      values = aadt_df$aadt_diff,
      title = "Differanse",
      opacity = 0.8,
      labFormat = labelFormat(big.mark = " ")
      )
  
  return(aadt_map)
}

```

```{r map}
# TODO: show trps
create_aadt_comparison_map(matchende)
```


```{r plot}
matchende %>% 
  ggplot(
    aes(
      aadt_total, aadt_bal
      )
    ) +
  ggplot2::geom_point() +
  geom_abline(
    slope = 1,
    intercept = 0
  ) +
  xlim(0, 5e4) +
  ylim(0, 5e4) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90),
        panel.grid.minor.x = element_blank()) +
  #scale_fill_brewer(palette = "Set3") +
  labs(x = "\nNVDB", y = "Balansert AADT\n") +
  ggtitle("Balansert AADT sammenlignet med NVDB")
```





