---
title: "NRs rettede vegnettsgraf"
output: html_notebook
---

```{r setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(knitr)

source("H:/Programmering/R/byindeks/split_road_system_reference.R")

# knitr options ####
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      cache = FALSE)

# Map essentials ####
nvdb_map_url <-
  "https://nvdbcache.geodataonline.no/arcgis/rest/services/Trafikkportalen/GeocacheTrafikkJPG/MapServer/tile/{z}/{y}/{x}"

nvdb_map_attribution <-
  "NVDB, Geovekst, kommunene og Open Street Map contributors (utenfor Norge)"

nvdb_crs <- leafletCRS(
  crsClass = "L.Proj.CRS", code = "EPSG:25833",
  proj4def = "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs",
  resolutions = c(
    21674.7100160867,
    10837.35500804335,
    5418.677504021675,
    2709.3387520108377,
    1354.6693760054188,
    677.3346880027094,
    338.6673440013547,
    169.33367200067735,
    84.66683600033868,
    42.33341800016934,
    21.16670900008467,
    10.583354500042335,
    5.291677250021167,
    2.6458386250105836,
    1.3229193125052918,
    0.6614596562526459,
    0.33072982812632296,
    0.16536491406316148
  ),
  origin = c(-2500000.0, 9045984.0))
```

```{r file_path, include=FALSE}
geopackage_file <- "nr/graf_dir_maincomp_20210505.gpkg"

layers <- sf::st_layers(geopackage_file) 

layer_size <- layers$features %>% 
  tibble::as_tibble()
```

```{r edges, message=FALSE}
#edge_query <- "SELECT * FROM \"edges_main_dir\" LIMIT 10"

edge_query <- "SELECT * FROM \"edges_main_dir\" WHERE roadref_category IN ('E') AND roadref_number IN ('134')"

edges_selected <- 
  sf::st_read(geopackage_file, "edge_main_dir", as_tibble = TRUE, query = edge_query) %>% 
  sf::st_zm(drop = T, what = "ZM") %>% 
  sf::st_transform("+proj=longlat +datum=WGS84") %>% 
  dplyr::mutate(across(starts_with("AADT"), floor)) %>% 
  dplyr::mutate(aadt = AADT_ALLE_MIN,
                aadt = dplyr::case_when(
                  aadt == 0 ~ NA_real_, 
                  TRUE ~ aadt),
                link_label = paste(aadt, sep = "<br/>"),
                link_label = lapply(link_label, htmltools::HTML),
                road_reference_split = stringr::str_split_fixed(ROADREF_START, ",", 2),
                road_reference = road_reference_split[,1]) %>% 
  split_road_system_reference() %>% 
  dplyr::select(ID, TOPOLOGYLEVEL, road_reference, ROADREF_START, ROADREF_END,
                med_metrering, KOMMENTAR_TOI, kobling, aadt,# starts_with("AADT_ALLE"),
                merknad, pred_lane, MD_norm, link_label)

edges_selected_with <- edges_selected %>% 
  dplyr::filter(med_metrering == 1)

maximum_aadt <- edges_selected %>% 
  sf::st_drop_geometry() %>% 
  dplyr::filter(!is.na(aadt)) %>% 
  dplyr::select(aadt) %>% 
  max()

minimum_aadt <- edges_selected %>% 
  sf::st_drop_geometry() %>% 
  dplyr::filter(!is.na(aadt)) %>% 
  dplyr::select(aadt) %>% 
  min()


color_levels <- seq(24, maximum_aadt)
color_gradient <- grDevices::colorRampPalette(c("green", "blue", "violet"))(length(color_levels))
color_gradient_df <- data.frame(aadt = color_levels,
                                color = color_gradient)

edges_selected_with_color <- edges_selected_with %>% 
  dplyr::left_join(color_gradient_df) %>% 
  dplyr::mutate(color = dplyr::if_else(is.na(color), "#000000", color))

unique_arranged_colors <- edges_selected_with_color %>% 
  sf::st_drop_geometry() %>% 
  dplyr::filter(!is.na(aadt)) %>% 
  dplyr::arrange(aadt) %>% 
  dplyr::select(color) %>% 
  unique()
```

```{r nodes}
# Tilhørende kryss
unique_start_node_ids <- edges_selected$START_NODE_OID %>% 
   unique()
unique_end_node_ids <- edges_selected$END_NODE_OID %>% 
   unique()
 
unique_node_ids <- c(unique_start_node_ids, unique_end_node_ids) %>% 
  unique() %>% 
  stringr::str_c(collapse = "\', \'")
 
node_query = paste0("SELECT * FROM \"nodes_main_dir\" WHERE FEATURE_OID IN (",
                     "\'", unique_node_ids, "\'", ")")
 
nodes <- sf::st_read(geopackage_file, "nodes_main_dir",
                     as_tibble = TRUE,
                      query = node_query) %>% 
   sf::st_zm(drop = T, what = "ZM") %>%
   sf::st_transform("+proj=longlat +datum=WGS84")
```

```{r map}
pal <- leaflet::colorNumeric(
    palette = unique_arranged_colors$color,
    domain = edges_selected_with_color$aadt,
    na.color = "#000000"
  )


leaflet(width = "100%",
        height = 700,
        options = leafletOptions(crs = nvdb_crs,
                                 zoomControl = F)) %>%
  addTiles(urlTemplate = nvdb_map_url,
           attribution = nvdb_map_attribution) %>%
  addPolylines(data = edges_selected_with_color,
               popup = ~link_label,
               color = edges_selected_with_color$color,
               opacity = 0.9,
               highlightOptions = highlightOptions(bringToFront = TRUE,
                                                   sendToBack = FALSE,
                                                   color = "white",
                                                   opacity = .8)) %>% 
  # addCircleMarkers(data = nodes,
  #                  popup = ~FEATURE_OID,
  #                  radius = 2,
  #                  stroke = FALSE,
  #                  fillOpacity = 0.5,
  #                  fill = TRUE,
  #                  fillColor = "black") %>% 
  addLegend("bottomright", pal = pal, values = edges_selected_with_color$aadt,
            title = "ÅDT",
            opacity = 1)
```