---
title: "Vegnettsgraf"
output: html_notebook
---

```{r setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(knitr)

# knitr options ####
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      cache = FALSE)

# Map essentials ####
nvdb_map_url <-
  "https://nvdbcache.geodataonline.no/arcgis/rest/services/Trafikkportalen/GeocacheTrafikkJPG/MapServer/tile/{z}/{y}/{x}"

nvdb_map_attribution <-
  "NVDB, Geovekst, kommunene og Open Street Map contributors (utenfor Norge)"

nvdb_crs <- leafletCRS(
  crsClass = "L.Proj.CRS", code = "EPSG:25833",
  proj4def = "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs",
  resolutions = c(
    21674.7100160867,
    10837.35500804335,
    5418.677504021675,
    2709.3387520108377,
    1354.6693760054188,
    677.3346880027094,
    338.6673440013547,
    169.33367200067735,
    84.66683600033868,
    42.33341800016934,
    21.16670900008467,
    10.583354500042335,
    5.291677250021167,
    2.6458386250105836,
    1.3229193125052918,
    0.6614596562526459,
    0.33072982812632296,
    0.16536491406316148
  ),
  origin = c(-2500000.0, 9045984.0))
```

```{r file_path, include=FALSE}
geopackage_file <- "nr/graf_undir_dekomp_001-392_20210414.gpkg"

layers <- sf::st_layers(geopackage_file) 

layer_size <- layers$features %>% 
  tibble::as_tibble()
```


```{r functions, message=FALSE}
#top_row_query <- "SELECT * FROM \"TrafikkLenker\" LIMIT 10"

read_layer_number <- function(layer_number) {
  
  edge_layer_name <- paste0("edges_all_", layer_number)

  edge_query <- paste0("SELECT * FROM \"", edge_layer_name, "\"")
  #edge_query <- paste0("SELECT roadref_category, geom FROM \"", edge_layer_name, "\"")
  # TODO: check all(is.na(st_dimension(edges$geom)))
  # remove empty?

  edges_selected <- sf::st_read(geopackage_file, edge_layer_name,
                                        as_tibble = TRUE,
                                        query = edge_query) %>% 
    sf::st_zm(drop = T, what = "ZM") %>% 
    sf::st_transform("+proj=longlat +datum=WGS84")
  
  
  node_layer_name <- paste0("nodes_all_", layer_number)

  node_query <- paste0("SELECT * FROM \"", node_layer_name, "\"")
  
  nodes_selected <- sf::st_read(geopackage_file, node_layer_name,
                                        as_tibble = TRUE,
                                        query = node_query) %>% 
    sf::st_zm(drop = T, what = "ZM") %>% 
    sf::st_transform("+proj=longlat +datum=WGS84")
  
  return_list <- list(edges_selected, nodes_selected)
  
  return(return_list)  
}

fetch_road_category_from_layer_1 <- function(road_category) {
  
  # road_category must be one of R, F, K
  road_category_string <- dplyr::case_when(
    road_category == "R" ~ "'E', 'R'",
    road_category == "F" ~ "'F'",
    road_category == "K" ~ "'K'"
  )
  
  edge_layer_name <- paste0("edges_all_", "1")  
  edge_query <- paste0("SELECT * FROM \"", edge_layer_name, "\" WHERE roadref_category IN(",
                       road_category_string, ")")  
  
  edges_selected <- sf::st_read(geopackage_file, edge_layer_name,
                              as_tibble = TRUE,
                              query = edge_query) %>% 
  sf::st_zm(drop = T, what = "ZM") %>% 
  sf::st_transform("+proj=longlat +datum=WGS84") %>% 
  dplyr::select(ID, START_NODE_OID, END_NODE_OID, DIRECTION, 
                ROADREF_CATEGORY:ROADREF_END)
  
  unique_start_node_ids <- edges_selected$START_NODE_OID %>% 
   unique()
  unique_end_node_ids <- edges_selected$END_NODE_OID %>% 
     unique()
   
  unique_node_ids <- c(unique_start_node_ids, unique_end_node_ids) %>% 
    unique() %>% 
    stringr::str_c(collapse = "\', \'")
   
  node_layer_name <- paste0("nodes_all_", "1")
  
  node_query <- paste0("SELECT * FROM \"", node_layer_name, "\"WHERE FEATURE_OID IN (",
                       "\'", unique_node_ids, "\'", ")")
  
  
  nodes_selected <- sf::st_read(geopackage_file, node_layer_name,
                                        as_tibble = TRUE,
                                        query = node_query) %>% 
    sf::st_zm(drop = T, what = "ZM") %>% 
    sf::st_transform("+proj=longlat +datum=WGS84")
  
  layer_list <- list(edges_selected, nodes_selected)
  
 return(layer_list) 
}

#edge_query <- paste0("SELECT roadref_category, geom FROM \"", edge_layer_name, "\"")
# TODO: check all(is.na(st_dimension(edges$geom)))
# remove empty?

create_edge_node_map <- function(layer_list) {
  
  leaflet(width = "100%",
          height = 700,
          options = leafletOptions(crs = nvdb_crs,
                                   zoomControl = F)) %>%
    addTiles(urlTemplate = nvdb_map_url,
             attribution = nvdb_map_attribution) %>%
    addPolylines(data = layer_list[[1]],
                 #popup = ~link_label,
                 highlightOptions = highlightOptions(bringToFront = TRUE,
                                                     sendToBack = FALSE,
                                                     color = "red",
                                                     opacity = 0.6)) %>% 
    addCircleMarkers(data = layer_list[[2]],
                     #popup = ~FEATURE_OID,
                     radius = 5,
                     stroke = FALSE,
                     fillOpacity = 0.9,
                     fill = TRUE,
                     fillColor = "black")
}
```


## Hovedkomponenten

### Riksveger
```{r layer_r, include=FALSE}
#layer_1 <- read_layer_number(1)
#create_edge_node_map(layer_1)
# Too much data at once, splitting by road category

layer_1_R <- "R" %>% 
  fetch_road_category_from_layer_1()
```

```{r map_main_r}
create_edge_node_map(layer_1_R)
```


### Fylkesveger
```{r layer_f, include=FALSE}
layer_1_F <- "F" %>% 
  fetch_road_category_from_layer_1()
```

```{r map_main_f}
create_edge_node_map(layer_1_F)
```



## Den nest største komponenten


```{r layer_2}
layer_2 <- read_layer_number(2)
create_edge_node_map(layer_2)
#links_2 <- layer_2[[1]]
#nodes_2 <- layer_2[[2]]
```


## Tredje største

```{r layer_3}
layer_3 <- read_layer_number(3)
create_edge_node_map(layer_3)
links_3 <- layer_3[[1]]
#nodes_2 <- layer_2[[2]]
```

## De minste komponentene

```{r layer_x}
layer_x <- read_layer_number(390)
create_edge_node_map(layer_x)

# Gjenstår: 71 - 389
# Check road cat
# Plot all in one
```



```{r read_n}
read_n_layers <- function(start_n, stop_n) {
  
  layer_n <- read_layer_number(start_n)
  edges <- layer_n[[1]]
  nodes <- layer_n[[2]]
  
  start_m <- start_n + 1
  
  for(n in start_m:stop_n) {
    
    layer_m <- read_layer_number(n)
    
    edges <- bind_rows(edges,
                       layer_m[[1]])
    
    nodes <- bind_rows(nodes,
                       layer_m[[2]])
  }
  
  layer_list <- list(edges, nodes)
  
  return(layer_list)
}
```


```{r map_n}
layer_x <- read_n_layers(101, 389)
create_edge_node_map(layer_x)
```


