---
title: "Vehicle Classification in Norway"
output: html_notebook
---


```{r setup, include = FALSE, echo = FALSE}
# Packages
library(tidyverse)
library(jsonlite)
library(flextable)
library(httr)
library(writexl)

# knitr options
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE)

source("get_from_data_norge.R")
```

Here comes something...
```{r getdata}
# Must have four data sets

# All (61 rows)
vehicle_groups <- get_vehicle_groups()

vehicle_technical_codes <- get_technical_codes()

vehicle_info_fields <- get_vehicle_info_fields()

vehicle_info <- get_vehicle_info("O3")

traffic_data_relevant_columns <- c("tekn_aksler",
                                   "tekn_aksler_drift", 
                                   "tekn_avreg_dato", 
                                   "tekn_drivst",
                                   "tekn_egenvekt",
                                   "tekn_euronorm_ny",
                                   "tekn_hybrid",
                                   "tekn_hybrid_kategori",
                                   "tekn_kjtgrp", 
                                   "tekn_last_1",
                                   "tekn_last_2",
                                   "tekn_last_3",
                                   "tekn_lengde", 
                                   "tekn_luft_1",
                                   "tekn_luft_2",
                                   "tekn_luft_3",
                                   "tekn_merkenavn",
                                   "tekn_minavst_ms1",
                                   "tekn_minavst_ms2",
                                   "tekn_reg_aar", 
                                   #"tekn_reg_status", 
                                   "tekn_thv_m_brems",
                                   "tekn_thv_u_brems",
                                   "tekn_tknavn",
                                   "tekn_totvekt", 
                                   "tekn_vogntogvekt"
                                   )

# A subset
vegtek_columns_to_be_removed <- c("tekn_drivst",
                                  "tekn_euronorm_ny",
                                  "tekn_hybrid",
                                  "tekn_hybrid_kategori",
                                  "tekn_merkenavn")

vehicle_info %>% 
        dplyr::select(tidyselect::all_of(traffic_data_relevant_columns)) %>% 
        write.csv2("kjoretoy_O3.csv",
                   row.names = FALSE)

vehicle_info %>% 
        dplyr::select(tidyselect::all_of(traffic_data_relevant_columns)) %>% 
        dplyr::select(!tidyselect::all_of(vegtek_columns_to_be_removed)) %>% 
        writexl::write_xlsx(path = "kjoretoy_O3.xlsx")

```

